### ISSUE TITLE
Example for using as blueprint? 

### ISSUE THREAD

**Issue by dubh3124** [factset/quart-openapi#7]
Is there a way to use blueprints similar to the way Flask-Restplus uses blueprints?

https://flask-restplus.readthedocs.io/en/stable/scaling.html

**Comment by zeroshade** [comment]
I'll take a look. I didn't code the blueprints in like Flask-restplus does, but I'll see how difficult it would be to add

**Comment by zeroshade** [comment]
So doing a little bit of research out looks like blueprints will currently work as shown in the Quart documentation and then you can call `register_blueprint` on your `Pint` instance and it will work as expected. However since I don't provide any wrapper for blueprints, like how flask_Restplus's API object can wrap a blueprint, you can't yet get the benefits of models, documentation and class based resource stuff when defining the blueprint.

I'll work on adding a blueprint equivalent of the `Pint` class, of course PRs are always welcome :)
